import { Page } from './page'

export const PAGES: Page[] = [
    {id: 1, chapterid: 1, content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam neque tortor, imperdiet at vulputate at, efficitur vel metus. Mauris a risus ut neque tempor porta. Ut fringilla ligula eu bibendum molestie. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam sed tempus mauris. Curabitur ut felis pellentesque, porta tortor nec, ullamcorper lacus. Nam sodales cursus leo, at pulvinar augue venenatis at. Etiam eget magna metus. Morbi venenatis mattis odio, a pellentesque elit elementum ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sed augue sollicitudin, mollis eros a, finibus nisi. Nulla fermentum a leo eu posuere. Maecenas quis nunc id velit laoreet maximus. Fusce euismod id magna at porttitor. Phasellus ac tincidunt risus.' },
    {id: 2, chapterid: 1, content: 'Nullam condimentum efficitur velit, at iaculis nulla fringilla quis. Sed lacinia imperdiet elit rutrum pulvinar. Phasellus tincidunt elit ut orci dignissim faucibus. Suspendisse lobortis condimentum sagittis. Morbi molestie finibus ex. Nulla elementum nisl mauris, ut condimentum ipsum facilisis eu. Vestibulum laoreet laoreet laoreet. Pellentesque vulputate fringilla lectus at commodo. Suspendisse augue urna, convallis in accumsan eget, mattis nec purus. Sed tincidunt neque eget consequat aliquam.' },
    {id: 3, chapterid: 1, content: 'Sed tristique, turpis a volutpat aliquet, nulla leo mollis enim, finibus vulputate est eros ut est. Nam nec nisl non risus commodo lobortis. Nullam quis magna volutpat, interdum turpis sed, pulvinar diam. Aliquam eget arcu ullamcorper, sollicitudin felis a, placerat lectus. Morbi in sollicitudin quam. In eu vehicula eros. Pellentesque dictum dolor feugiat aliquet finibus. Nulla maximus maximus ex at venenatis. Vivamus mollis fringilla ligula, non vulputate purus venenatis ultricies. Donec libero diam, eleifend a enim quis, interdum vestibulum lectus. Curabitur ut porta eros.' },
    {id: 4, chapterid: 2, content: 'Proin in suscipit mauris, porttitor scelerisque libero. Phasellus vel metus bibendum, rhoncus nibh ac, mattis est. Sed sit amet bibendum ipsum. Aliquam hendrerit ultricies leo, vitae imperdiet sem aliquet et. Praesent consectetur tincidunt dapibus. Nunc massa nisi, viverra eu faucibus vel, tincidunt in turpis. Aliquam id orci lorem. Morbi vestibulum porttitor pharetra. Maecenas sagittis diam at ipsum facilisis, nec ultricies nulla euismod. Nam in lacinia nisi, in ornare tortor. Aliquam at nisi ultricies, vehicula lorem id, egestas nulla.' },
    {id: 5, chapterid: 2, content: 'Integer facilisis arcu vel risus accumsan, id semper ex pretium. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce laoreet nibh nec diam lacinia convallis. Morbi nulla libero, vehicula vitae massa sed, placerat suscipit diam. Aliquam id leo diam. Nam enim ex, venenatis sed libero quis, pellentesque varius quam. Nam maximus feugiat dolor in tincidunt. Aliquam eget varius nunc. In lobortis gravida justo, quis malesuada lorem blandit ac. Quisque id iaculis tortor, scelerisque ornare turpis. Ut gravida ante ac aliquet vestibulum. Aliquam pretium nunc in suscipit iaculis.' },
    {id: 6, chapterid: 2, content: 'Nullam tellus ligula, imperdiet nec lorem at, efficitur molestie est. Mauris sagittis lacus id sodales finibus. Praesent eu velit nisl. Donec nunc lorem, porta ac risus nec, mollis tincidunt nulla. Donec vitae rutrum erat, consectetur posuere nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam placerat, lacus sit amet varius venenatis, lectus ipsum dignissim purus, et ullamcorper tortor orci id enim.' },
    {id: 7, chapterid: 3, content: 'Maecenas tincidunt dignissim mi, id rutrum elit pharetra id. Cras at nulla risus. Vivamus elementum quam et metus venenatis ultrices. Nulla ullamcorper rhoncus nulla in fringilla. Morbi at lacus ligula. Vivamus viverra imperdiet ipsum, ac luctus mauris dignissim ac. Aenean ornare sapien vel sapien finibus, ac commodo elit condimentum.' },
    {id: 8, chapterid: 3, content: 'Praesent vestibulum nec diam id volutpat. Suspendisse ac enim id libero pretium pretium ut ut orci. In a tincidunt leo, a luctus leo. Sed ac lacinia urna. Quisque ac quam ligula. In et dictum tellus. Nullam finibus ut augue sagittis hendrerit. Donec et leo vel lectus imperdiet tempor. Suspendisse facilisis mi id mattis auctor. Ut ac nulla non purus sodales venenatis scelerisque et eros. In semper diam vel sapien ultricies feugiat. Maecenas nec aliquam velit, sit amet pellentesque nulla. Suspendisse laoreet non sem ut tempus. Ut augue nibh, tincidunt eget magna quis, ultrices dignissim enim.' },
    {id: 9, chapterid: 3, content: 'Proin id ex id justo rutrum finibus. Donec vel neque et ligula dignissim tincidunt. Donec quis faucibus risus, vel auctor enim. Maecenas eleifend ipsum et odio accumsan, in varius lacus sagittis. Nunc pharetra gravida pharetra. Ut suscipit orci nec elit mattis, et lobortis orci tincidunt. Etiam fermentum lobortis eros eget scelerisque. Sed dignissim ex ut nisl consectetur lacinia. Fusce ac leo purus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam nec orci laoreet, fringilla tellus sed, maximus urna.' }
]